# Generated by Django 5.0.3 on 2024-04-09 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 9, 11, 31, 9, 506514, tzinfo=datetime.timezone.utc)),
        ),
    ]
