# Generated by Django 5.0.3 on 2024-04-12 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_shopuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 18, 54, 34, 519134, tzinfo=datetime.timezone.utc)),
        ),
    ]
